djangoSeminar/urls.py
from django.urls import path
from . import views

app_name = 'djangoSeminar'

urlpatterns = [
    path('', views.index, name='index'),
    path('mypage/', views.mypage, name='mypage'),
    path('temp/', views.temp, name='temp'),
    path('push_heart_button/', views.push_heart_button, name='push_heart_button'),
    path('date_selected/', views.date_selected, name='date_selected'),
]

hiccStudyPart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('djangoSeminar.urls')),
    path('admin/', admin.site.urls),
]

djangoSeminar/models.py
from django.db import models

# Create your models here.

djangoSeminar/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json

saved_id = 'hicc'
saved_pw = 'hicc2023'
heart_count = 0


def index(request):
    context = dict()
    if request.method == 'POST':
        id_ = request.POST.get('id_')
        pw = request.POST.get('pw')
        login_success = authenticate(id_, pw)

        if login_success:
            return redirect('djangoSeminar:mypage')
        else:
            context = {
                'login_success': login_success
            }

    return render(request, 'djangoSeminar/index.html', context)


def authenticate(id_, pw):
    if saved_id == id_ and saved_pw == pw:
        return True
    else:
        return False


def mypage(request):
    return render(request, 'djangoSeminar/mypage.html')


def temp(request):
    return render(request, 'djangoSeminar/temp.html')


def push_heart_button(request):
    if request.method == 'POST':
        global heart_count
        heart_count = int(heart_count) + 1

        context = {
            'heart_count': heart_count
        }

        return JsonResponse(context)


def date_selected(request):
    if request.method == 'POST':
        result = json.loads(request.body)
        date = result['date']
        context = {
            'selected': f'선택한 날짜는 {date} 입니다.'
        }

        # json_dumps_params 이 부분은 한글이 깨지지 않도록 도와줌
        return JsonResponse(context, json_dumps_params={'ensure_ascii': False})

djangoSeminar/templates/djangoSeminar/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "css/index.css" %}">
{% endblock %}

{% block content %}
    <h1 class="hello">hello world</h1>
    <a href="{% url 'djangoSeminar:temp' %}">a태그로 페이지 이동</a>
    <form action="{% url 'djangoSeminar:index' %}" method="POST">
    {% csrf_token %}
        <h2>sign in</h2>
        <div class="input_row">
            <label for="id_">ID</label>
            <input id="id_" name="id_" />
        </div>
        <div class="input_row">
            <label for="pw">PW</label>
            <input id="pw" name="pw" type="password" />
        </div>
        <button type="submit">확인</button>
        <span class="result"></span>
    </form>
{% endblock %}

{% block js %}
    <script>
        const is_authenticate = JSON.parse({{ login_success|lower }});
    </script>
    <script src="{% static "js/index.js" %}"></script>
{% endblock %}

djangoSeminar/templates/djangoSeminar/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "css/mypage.css" %}">
{% endblock %}

{% block content %}
    <h1>안녕하세요</h1>
    <section>
        <div class="partition">
            <button class="heart_button" type="button">좋아요</button>
            <span class="heart_count">{{ number }}</span>
        </div>
        <div class="partition">
            <input class="date" type="date" name="date" />
            <button class="date_button" type="button">선택</button>
            <span class="date_print"></span>
        </div>
    </section>
{% endblock %}

{% block js %}
    <script>
        const heart_url = '{% url 'djangoSeminar:push_heart_button' %}';
        const date_url = '{% url 'djangoSeminar:date_selected' %}';
    </script>
    <script src="{% static "js/mypage.js" %}"></script>
{% endblock %}

djangoSeminar/templates/djangoSeminar/temp.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "css/index.css" %}">
{% endblock %}

{% block content %}
    <h1>a태그로 페이지 이동 결과</h1>
{% endblock %}

{% block js %}
    <script src="{% static "js/index.js" %}"></script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>HICC Django Seminar</title>
    {% block css %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</body>
</html>